# Generated by Django 6.0.7 on 2026-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_admin_area', 'Can view the admin area')],
                'default_permissions': (),
            },
        ),
    ]
